# Generated by Django 4.2 on 2023-04-21 15:28

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owes', jsonfield.fields.JSONField(default=dict)),
                ('owedby', jsonfield.fields.JSONField(default=dict)),
                ('balance', models.FloatField()),
            ],
        ),
    ]
