# Generated by Django 4.2 on 2023-04-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOU', '0003_alter_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
