# Generated by Django 4.2 on 2023-04-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOU', '0004_alter_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
